### ISSUE TITLE
Add a newsletter / release notes type of section for ngen, troute, NGIAB

### ISSUE THREAD

**Issue by arpita0911patel** [CIROH-UA/ciroh-ua_website#28]

**Comment by ZacharyWills** [comment]
My note on formatting, timing, and what to include:

Start at the largest conglomerate:
### NGIAB
-PR merges
-Releases
-tutorials
-etc

Then add the component updates:
##NGEN
##T-Route
##Hydrofabric
##Forcings

Lastly we can have a writeup about any usage strategies or methods. This will be a good place for the model formulations team to kick in anything new from their side.

**Comment by ZacharyWills** [comment]
### FIRST DRAFT, Not Finished


Post Date: Nov. 6th 2023
Start at the largest conglomerate:

###NGIAB

-PR merges
-Releases
-tutorials
-etc

Then add the component updates:
###NGEN
8 Pull Requests were worked on in October, focused on performance improvements and spatial domain tooling.
###T-Route
22 Pull Requests were worked on in October with 11 merged, and a focus on testing and getting bugs fixed 
###Hydrofabric
Lynker is proud to support CIROH with a freely accessable resource for geospatial data: https://www.lynker-spatial.com/

In addition to the new location, the [command-line tool](https://github.com/LynkerIntel/hfsubset) for sub-setting the Hydrofabric is getting an update as well! The tool allows users to extract the upstream area of a given location from the CONUS datasets to ensure that getting the spatial domain on which to run your NextGen formulation is as easy as possible. 

The new version allows users to specify an outlet by location, NHDPlus COMID, NextGen ID, or hydrolocation (NWIS gage, NID dams, HUC12 outlets etc.). The new version also also provides [NLDI](https://waterdata.usgs.gov/blog/nldi-intro/) and [Geoconnex](https://internetofwater.org/geoconnex/) support as well as the ability to generate subsets from the [reference](https://noaa-owp.github.io/hydrofabric/articles/02-design-deep-dive.html), [refactored](https://noaa-owp.github.io/hydrofabric/articles/03-processing-deep-dive.html), and [NextGen](https://noaa-owp.github.io/hydrofabric/articles/04-data-model-deep-dive.html) networks!

###Forcings
 A new tool that has been made public is the forcingprocessor (https://github.com/CIROH-UA/ngen-datastream/tree/main/forcingprocessor). This tool converts any National Water Model based forcing files into ngen forcing files. This process can be an intensive operation in compute, memory, and IO, so this tool facilitates generating ngen input and ultimately makes running ngen more accessible.

**Comment by arpita0911patel** [comment]
This is covered in https://github.com/CIROH-UA/ciroh-ua_website/pull/33
