### ISSUE TITLE
Add link to variable descriptions

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/ciroh-ua_website#55]
https://github.com/CIROH-UA/ciroh-ua_website/blob/ccb5d197d215f82c6b70dc152932708394858535/docs/products/tools/dataaccess/dataaccess.md?plain=1#L45

Expand the description of the variables by linking to this page: https://water.noaa.gov/about/output_file_contents

**Comment by arpita0911patel** [comment]
Closing this long standing ticket as link seems to be broken.
Error 404
The page you are looking for is not available.
